//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingSeb.ExpressionEvaluator.Tests {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingSeb.ExpressionEvaluator.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0001 */
        ///x = 0;
        ///result = &quot;&quot;;
        ///
        ///while(x &lt; 5)
        ///{
        ///	result += $&quot;{x},&quot;;
        ///	x++;
        ///}
        ///
        ///result.Remove(result.Length - 1); 的當地語系化字串。
        /// </summary>
        public static string Script0001 {
            get {
                return ResourceManager.GetString("Script0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0002 */
        ///result = &quot;&quot;;
        ///
        ///for(x = 0; x &lt; 5;x++)
        ///{
        ///	result += $&quot;{x},&quot;;
        ///}
        ///
        ///result.Remove(result.Length - 1); 的當地語系化字串。
        /// </summary>
        public static string Script0002 {
            get {
                return ResourceManager.GetString("Script0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0003 */
        ///result = &quot;&quot;;
        ///
        ///for(x = 0; x &lt; 5;x++)
        ///	result += $&quot;{x},&quot;;
        ///
        ///result.Remove(result.Length - 1); 的當地語系化字串。
        /// </summary>
        public static string Script0003 {
            get {
                return ResourceManager.GetString("Script0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0004 */
        ///x = [valx];
        ///y = [valy];
        ///result = 0;
        ///
        ///if(y != 0)
        ///{
        ///	result = 1;
        ///}
        ///else if(x == 0)
        ///{
        ///	result = 2;
        ///}
        ///else if(x &lt; 0)
        ///{
        ///	result = 3;
        ///}
        ///else
        ///{
        ///	result = 4;
        ///}
        ///
        ///result; 的當地語系化字串。
        /// </summary>
        public static string Script0004 {
            get {
                return ResourceManager.GetString("Script0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0005 */
        ///x = [valx];
        ///y = [valy];
        ///result = 0;
        ///
        ///if(y != 0)
        ///	result = 1;
        ///else if(x == 0)
        ///	result = 2;
        ///else if(x &lt; 0)
        ///	result = 3;
        ///else
        ///	result = 4;
        ///
        ///result; 的當地語系化字串。
        /// </summary>
        public static string Script0005 {
            get {
                return ResourceManager.GetString("Script0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0006 */
        ///List(1,2,3,4)
        ///    .Find((element) =&gt; 
        ///    {
        ///        x = 2 + 2;
        ///        element == 3;
        ///    }); 的當地語系化字串。
        /// </summary>
        public static string Script0006 {
            get {
                return ResourceManager.GetString("Script0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0007 */
        ///x = 4;
        ///y = 0;
        ///
        ///if(x == 4)
        ///	y = List(1,2,3,4)
        ///		.Find((element) =&gt; 
        ///		{
        ///			x = 2 + 2;
        ///			element == 3;
        ///		}) + 10;
        ///
        /// 的當地語系化字串。
        /// </summary>
        public static string Script0007 {
            get {
                return ResourceManager.GetString("Script0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0008 */
        ///x = [valx];
        ///
        ///if(x == 0)
        ///	return 2;
        ///	
        ///x; 的當地語系化字串。
        /// </summary>
        public static string Script0008 {
            get {
                return ResourceManager.GetString("Script0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0009 */
        ///x = &quot;&quot;;
        ///
        ///for(i = 0; i &lt; 10; i++)
        ///{
        ///	if(i == 3)
        ///		continue;
        ///		
        ///	x += $&quot;{i},&quot;;
        ///	
        ///	if(i == 6)
        ///		break;
        ///}
        ///	
        ///x; 的當地語系化字串。
        /// </summary>
        public static string Script0009 {
            get {
                return ResourceManager.GetString("Script0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0010 */
        ///x = &quot;&quot;;
        ///i = -1;
        ///
        ///while(i &lt; 10)
        ///{
        ///	i++;
        ///
        ///	if(i == 3)
        ///		continue;
        ///		
        ///	x += $&quot;{i},&quot;;
        ///	
        ///	if(i == 6)
        ///		break;
        ///}
        ///	
        ///x; 的當地語系化字串。
        /// </summary>
        public static string Script0010 {
            get {
                return ResourceManager.GetString("Script0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0011 */
        ///list = List(5,5,5,5,5,5,5,5,5,5,5);
        ///
        ///list[0] = 8;
        ///list[1] += 6;
        ///list[2] -= 2;
        ///list[3] *= 3;
        ///list[4] /= 2;
        ///list[5] %= 2;
        ///list[6] ^= 3;
        ///list[7] &amp;= 3;
        ///list[8] |= 3;
        ///list[9] &lt;&lt;= 2;
        ///list[10] &gt;&gt;=2;
        ///
        ///return list.Json; 的當地語系化字串。
        /// </summary>
        public static string Script0011 {
            get {
                return ResourceManager.GetString("Script0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0012 */
        ///list = List(5,5,5,5,5,5);
        ///
        ///list[0]++;
        ///list[1]--;
        ///list[2] += list[3]++; 
        ///list[4] += list[5]--;
        ///
        ///return list.Json; 的當地語系化字串。
        /// </summary>
        public static string Script0012 {
            get {
                return ResourceManager.GetString("Script0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0013 */
        ///x = 0;
        ///result = &quot;&quot;;
        ///
        ///do
        ///{
        ///	result += $&quot;{x},&quot;;
        ///	x++;
        ///}
        ///while(x &lt; 5);
        ///
        ///result.Remove(result.Length - 1); 的當地語系化字串。
        /// </summary>
        public static string Script0013 {
            get {
                return ResourceManager.GetString("Script0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0014 */
        ///x = 0;
        ///result = &quot;&quot;;
        ///
        ///do
        ///{
        ///	result += $&quot;{x},&quot;;
        ///	x++;
        ///}
        ///while(false);
        ///
        ///result.Remove(result.Length - 1); 的當地語系化字串。
        /// </summary>
        public static string Script0014 {
            get {
                return ResourceManager.GetString("Script0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0015 */
        ///x = 0;
        ///result = &quot;&quot;;
        ///
        ///while(false)
        ///{
        ///	result += $&quot;{x},&quot;;
        ///	x++;
        ///}
        ///
        ///
        ///result; 的當地語系化字串。
        /// </summary>
        public static string Script0015 {
            get {
                return ResourceManager.GetString("Script0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0016 */
        ///Add = (x, y) =&gt; x + y;
        ///
        ///return Add(3, 4); 的當地語系化字串。
        /// </summary>
        public static string Script0016 {
            get {
                return ResourceManager.GetString("Script0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0017 */
        ///
        ///FirstFunc = x =&gt; 
        ///{
        ///	y = 3;
        ///	return x + y; 
        ///};
        ///
        ///SecondFunc = (x, y) =&gt; FirstFunc(x) - y;
        ///
        ///return SecondFunc(5, 2); 的當地語系化字串。
        /// </summary>
        public static string Script0017 {
            get {
                return ResourceManager.GetString("Script0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0018 */
        ///
        ///result = string.Empty;
        ///elements = List(&quot;This&quot;, &quot;is&quot;, &quot;a&quot;, &quot;splitted&quot;, &quot;text&quot;);
        ///
        ///foreach(element in elements)
        ///{
        ///	result += element;
        ///	result += &quot; &quot;;
        ///}
        ///
        ///result.Remove(result.Length - 1); 的當地語系化字串。
        /// </summary>
        public static string Script0018 {
            get {
                return ResourceManager.GetString("Script0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0019 */
        ///myVar = new ExpandoObject();
        ///
        ///myVar.X = 23.5;
        ///myVar.Y = 34.8;
        ///
        ///return myVar.X + myVar.Y; 的當地語系化字串。
        /// </summary>
        public static string Script0019 {
            get {
                return ResourceManager.GetString("Script0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0020 */
        ///myVar = new ExpandoObject();
        ///
        ///myVar[&quot;X&quot;] = 23.5;
        ///myVar[&quot;Y&quot;] = 34.8;
        ///
        ///return myVar.X + myVar.Y; 的當地語系化字串。
        /// </summary>
        public static string Script0020 {
            get {
                return ResourceManager.GetString("Script0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0021 */
        ///myVar = new ExpandoObject();
        ///
        ///myVar[&quot;X&quot;] = 23.5;
        ///myVar[&quot;Y&quot;] = 34.8;
        ///
        ///return myVar[&quot;X&quot;] + myVar[&quot;Y&quot;]; 的當地語系化字串。
        /// </summary>
        public static string Script0021 {
            get {
                return ResourceManager.GetString("Script0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0022 */
        ///myVar = new ExpandoObject();
        ///
        ///myVar.X = 23.5;
        ///myVar.Y = 34.8;
        ///
        ///return myVar[&quot;X&quot;] + myVar[&quot;Y&quot;]; 的當地語系化字串。
        /// </summary>
        public static string Script0022 {
            get {
                return ResourceManager.GetString("Script0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0023 */
        ///myVar = new ExpandoObject();
        ///
        ///myVar.X = 2;
        ///myVar.X++;
        ///myVar[&quot;Y&quot;] = 1;
        ///myVar[&quot;Y&quot;]++;
        ///
        ///return myVar[&quot;X&quot;] + myVar.Y; 的當地語系化字串。
        /// </summary>
        public static string Script0023 {
            get {
                return ResourceManager.GetString("Script0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0024 */
        ///obj = new ExpandoObject();
        ///
        ///obj.Add = (x, y) =&gt; 
        ///{
        ///	text = &quot;The result is : &quot;;
        ///	return text + (x+y).ToString();
        ///};
        ///
        ///return obj.Add(3, 4); 的當地語系化字串。
        /// </summary>
        public static string Script0024 {
            get {
                return ResourceManager.GetString("Script0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0025 */
        ///
        ///throw new Exception(&quot;Exception for test&quot;); 的當地語系化字串。
        /// </summary>
        public static string Script0025 {
            get {
                return ResourceManager.GetString("Script0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0026 */
        ///
        ///varçÿ = &quot;A value in diactitic varçÿ&quot;;
        ///
        ///áàâãåǎăāąæéèêëěēĕėęěìíîïīĭįĳóôõöōŏőøðœùúûüǔũūŭůűųýþÿŷıćĉċčçďđĝğġģĥħĵķĺļľŀłńņňŋñŕŗřśŝşšţťŧŵźżžÁÀÂÃÅǍĂĀĄÆÉÈÊËĚĒĔĖĘĚÌÍÎÏĪĬĮĲÓÔÕÖŌŎŐØÐŒÙÚÛÜǓŨŪŬŮŰŲÝÞŸŶIĆĈĊČÇĎĐĜĞĠĢĤĦĴĶĹĻĽĿŁŃŅŇŊÑŔŖŘŚŜŞŠŢŤŦŴŹŻŽß = &quot;very complex var&quot;;
        ///
        ///return $&quot;{varçÿ} &amp;&amp; {áàâãåǎăāąæéèêëěēĕėęěìíîïīĭįĳóôõöōŏőøðœùúûüǔũūŭůűųýþÿŷıćĉċčçďđĝğġģĥħĵķĺļľŀłńņňŋñŕŗřśŝşšţťŧŵźżžÁÀÂÃÅǍĂĀĄÆÉÈÊËĚĒĔĖĘĚÌÍÎÏĪĬĮĲÓÔÕÖŌŎŐØÐŒÙÚÛÜǓŨŪŬŮŰŲÝÞŸŶIĆĈĊČÇĎĐĜĞĠĢĤĦĴĶĹĻĽĿŁŃŅŇŊÑŔŖŘŚŜŞŠŢŤŦŴŹŻŽß}&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0026 {
            get {
                return ResourceManager.GetString("Script0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0027 */
        ///
        ///test = new áàâãåǎăāąæéèêëěēĕėęěìíîïīĭįĳóôõöōŏőøðœùúûüǔũūŭůűųýþÿŷıćĉċčçďđĝğġģĥħĵķĺļľŀłńņňŋñŕŗřśŝşšţťŧŵźżžÁÀÂÃÅǍĂĀĄÆÉÈÊËĚĒĔĖĘĚÌÍÎÏĪĬĮĲÓÔÕÖŌŎŐØÐŒÙÚÛÜǓŨŪŬŮŰŲÝÞŸŶIĆĈĊČÇĎĐĜĞĠĢĤĦĴĶĹĻĽĿŁŃŅŇŊÑŔŖŘŚŜŞŠŢŤŦŴŹŻŽß();
        ///
        ///return test.Přōþěŕŧÿ; 的當地語系化字串。
        /// </summary>
        public static string Script0027 {
            get {
                return ResourceManager.GetString("Script0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0028 */
        ///
        ///x = 5;
        ///y = 0;
        ///
        ///c = false;
        ///f = false;
        ///
        ///try
        ///{
        ///	x / y;
        ///}
        ///catch(exception)
        ///{
        ///	c = true;
        ///}
        ///finally
        ///{
        ///	f = true;
        ///}
        ///
        ///return $&quot;catch : {c}, finally : {f}&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0028 {
            get {
                return ResourceManager.GetString("Script0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0029 */
        ///
        ///x = 5;
        ///y = 0;
        ///
        ///c = false;
        ///f = false;
        ///
        ///try
        ///{
        ///	x / y;
        ///}
        ///finally
        ///{
        ///	ClassForTest1.StaticIntProperty = 20;
        ///	f = true;
        ///}
        ///
        ///return $&quot;catch : {c}, finally : {f}&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0029 {
            get {
                return ResourceManager.GetString("Script0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0030 */
        ///
        ///x = 5;
        ///y = 0;
        ///
        ///c = false;
        ///f = false;
        ///
        ///try
        ///{
        ///	x / y;
        ///}
        ///catch(exception)
        ///{
        ///	c = true;
        ///}
        ///
        ///return $&quot;catch : {c}, finally : {f}&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0030 {
            get {
                return ResourceManager.GetString("Script0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0031 */
        ///
        ///x = 5;
        ///y = 0;
        ///
        ///c = 0;
        ///f = false;
        ///
        ///try
        ///{
        ///	x / y;
        ///}
        ///catch(DivideByZeroException exception)
        ///{
        ///	c = 1;
        ///}
        ///catch(Exception exception)
        ///{
        ///	c = 2;
        ///}
        ///finally
        ///{
        ///	f = true;
        ///}
        ///
        ///return $&quot;catch : {c}, finally : {f}&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0031 {
            get {
                return ResourceManager.GetString("Script0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0032 */
        ///
        ///c = 0;
        ///f = false;
        ///
        ///try
        ///{
        ///	throw new Exception(&quot;My exception&quot;);
        ///}
        ///catch(DivideByZeroException exception)
        ///{
        ///	c = 1;
        ///}
        ///catch(Exception exception)
        ///{
        ///	c = 2;
        ///}
        ///finally
        ///{
        ///	f = true;
        ///}
        ///
        ///return $&quot;catch : {c}, finally : {f}&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0032 {
            get {
                return ResourceManager.GetString("Script0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0033 */
        ///
        ///array = Array.CreateInstance(typeof(int), 3);
        ///array[1] = 5;
        ///array.Json; 的當地語系化字串。
        /// </summary>
        public static string Script0033 {
            get {
                return ResourceManager.GetString("Script0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0034 */
        ///
        ///array = new int[3];
        ///array[1] = 5;
        ///array.Json; 的當地語系化字串。
        /// </summary>
        public static string Script0034 {
            get {
                return ResourceManager.GetString("Script0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0035 */
        ///
        ///array = new int[] {1, 2, 3};
        ///array.Json; 的當地語系化字串。
        /// </summary>
        public static string Script0035 {
            get {
                return ResourceManager.GetString("Script0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0036 */
        ///
        ///array = new int[3] {1, 2, 3};
        ///array.Json; 的當地語系化字串。
        /// </summary>
        public static string Script0036 {
            get {
                return ResourceManager.GetString("Script0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0037 */
        ///
        ///test = &quot;\&quot;&quot; ; 的當地語系化字串。
        /// </summary>
        public static string Script0037 {
            get {
                return ResourceManager.GetString("Script0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0038 */
        ///
        ///xmlTagRegexPattern = &quot;(?&lt;begining&gt;[&lt;]tag\\s+id\\s*[=]\\s*\&quot;A.Id.For.The_Tag[^\&quot;]*\&quot;\\s*version\\s*[=]\\s*\&quot;)(?&lt;version&gt;[^\&quot;]*)&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0038 {
            get {
                return ResourceManager.GetString("Script0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0039 */
        ///
        ///xmlTagRegexPattern = $&quot;(?&lt;begining&gt;[&lt;]tag\\s+id\\s*[=]\\s*{&apos;&quot;&apos;}A.Id.For.The_Tag[^{&apos;&quot;&apos;}]*{&apos;&quot;&apos;}\\s*version\\s*[=]\\s*{&apos;&quot;&apos;})(?&lt;version&gt;[^{&apos;&quot;&apos;}]*)&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0039 {
            get {
                return ResourceManager.GetString("Script0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0040 */
        ///
        ///xmlTagRegexPattern = $&quot;(?&lt;begining&gt;[&lt;]tag\\s+id\\s*[=]\\s*{&quot;\&quot;&quot;}A.Id.For.The_Tag[^{&quot;\&quot;&quot;}]*{&quot;\&quot;&quot;}\\s*version\\s*[=]\\s*{&quot;\&quot;&quot;})(?&lt;version&gt;[^{&quot;\&quot;&quot;}]*)&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0040 {
            get {
                return ResourceManager.GetString("Script0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0041 */
        ///
        ///xmlTagRegexPattern = $@&quot;(?&lt;begining&gt;[&lt;]tag\s+id\s*[=]\s*{&quot;\&quot;&quot;}A.Id.For.The_Tag[^{&quot;\&quot;&quot;}]*{&quot;\&quot;&quot;}\s*version\s*[=]\s*{&quot;\&quot;&quot;})(?&lt;version&gt;[^{&quot;\&quot;&quot;}]*)&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0041 {
            get {
                return ResourceManager.GetString("Script0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0042 */
        ///
        ///doubleQuoteChar = &apos;&quot;&apos;; 的當地語系化字串。
        /// </summary>
        public static string Script0042 {
            get {
                return ResourceManager.GetString("Script0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0043 */
        ///
        ///doubleQuoteString = $&quot;{&apos;&quot;&apos;}&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0043 {
            get {
                return ResourceManager.GetString("Script0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0044 */
        ///
        ///xmlTagRegexPattern = $@&quot;{ &apos;&quot;&apos; }&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0044 {
            get {
                return ResourceManager.GetString("Script0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0045 */
        ///
        ///xmlTagRegexPattern = $@&quot;(?&lt;begining&gt;[&lt;]tag\s+id\s*[=]\s*{&apos;&quot;&apos;}A.Id.For.The_Tag[^{&apos;&quot;&apos;}]*{&apos;&quot;&apos;}\s*version\s*[=]\s*{&apos;&quot;&apos;})(?&lt;version&gt;[^{&apos;&quot;&apos;}]*)&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0045 {
            get {
                return ResourceManager.GetString("Script0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0046 */
        ///
        ///xmlTagRegexPattern = $@&quot;(?&lt;begining&gt;[&lt;]tag\s+id\s*[=]\s*{ &apos;&quot;&apos; }A.Id.For.The_Tag[^{ &apos;&quot;&apos; }]*{ &apos;&quot;&apos; }\s*version\s*[=]\s*{ &apos;&quot;&apos; })(?&lt;version&gt;[^{ &apos;&quot;&apos; }]*)&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0046 {
            get {
                return ResourceManager.GetString("Script0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0047 */
        ///x = 5;
        ///y = ++x;
        ///$&quot;x:{x} y:{y}&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0047 {
            get {
                return ResourceManager.GetString("Script0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0048 */
        ///x = 5;
        ///y = --x;
        ///$&quot;x:{x} y:{y}&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0048 {
            get {
                return ResourceManager.GetString("Script0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0049 */
        ///P1 = 5;
        ///P2 = 6;
        ///P1 &lt; 1 &amp;&amp; P2 &gt; 3; 的當地語系化字串。
        /// </summary>
        public static string Script0049 {
            get {
                return ResourceManager.GetString("Script0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0050 */
        ///Json = &quot;hye&quot;;
        ///
        ///x = new ExpandoObject();
        ///x.Hello = 3;
        ///x.No = &quot;Yes&quot;;
        ///
        ///x.Json; 的當地語系化字串。
        /// </summary>
        public static string Script0050 {
            get {
                return ResourceManager.GetString("Script0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0051 */
        ///x = new ExpandoObject()
        ///{
        ///	Hello = 3,
        ///	No = &quot;Yes&quot;
        ///};
        ///
        ///x.Json; 的當地語系化字串。
        /// </summary>
        public static string Script0051 {
            get {
                return ResourceManager.GetString("Script0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0052 */
        ///
        ///Json = &quot;Yes&quot;;
        ///y = 3;
        ///
        ///x = new ExpandoObject()
        ///{
        ///	Hello = y,
        ///	No = Json
        ///};
        ///
        ///x.Json; 的當地語系化字串。
        /// </summary>
        public static string Script0052 {
            get {
                return ResourceManager.GetString("Script0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0053 */
        ///x = new 
        ///{
        ///	Hello = 3,
        ///	No = &quot;Yes&quot;
        ///};
        ///
        ///x.Json; 的當地語系化字串。
        /// </summary>
        public static string Script0053 {
            get {
                return ResourceManager.GetString("Script0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0054 */
        ///myStruct.myIntvalue = 3;
        ///myStruct.myStringValue = &quot;Test&quot;;
        ///
        ///return $&quot;Result {myStruct.myStringValue} {myStruct.myIntvalue}&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0054 {
            get {
                return ResourceManager.GetString("Script0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0055 */
        ///otherStruct.AnOtherIntValue = 5;
        ///
        ///otherStruct.nestedStruct = new StructForTest1()
        ///{ 
        ///	myIntvalue = 8, 
        ///	myStringValue = &quot;Hey&quot;
        ///};
        ///
        ///otherStruct.nestedStruct.myIntvalue = 9;
        ///
        ///return $&quot;Result {otherStruct.nestedStruct.myStringValue} {otherStruct.nestedStruct.myIntvalue}, {otherStruct.AnOtherIntValue}&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0055 {
            get {
                return ResourceManager.GetString("Script0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0056 */
        ///classStructContainer = new ClassStructContainer()
        ///{
        ///    nestedStructField = new StructForTest1()
        ///    {
        ///        myIntvalue = 8,
        ///        myStringValue = &quot;Hey&quot;
        ///    }
        ///};
        ///
        ///classStructContainer.nestedStructField.myIntvalue = 9;
        ///
        ///return $&quot;Result {classStructContainer.nestedStructField.myStringValue} {classStructContainer.nestedStructField.myIntvalue}&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0056 {
            get {
                return ResourceManager.GetString("Script0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0057 */
        ///classStructContainer = new ClassStructContainer()
        ///{
        ///    nestedStructField2 = new StructForTest3()
        ///    {
        ///        MyIntvalue = 8,
        ///        MyStringValue = &quot;Hey&quot;
        ///    }
        ///};
        ///
        ///classStructContainer.nestedStructField2.MyIntvalue = 9;
        ///
        ///return $&quot;Result {classStructContainer.nestedStructField2.MyStringValue} {classStructContainer.nestedStructField2.MyIntvalue}&quot;;
        /// 的當地語系化字串。
        /// </summary>
        public static string Script0057 {
            get {
                return ResourceManager.GetString("Script0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0058 */
        ///classStructContainer = new ClassStructContainer()
        ///{
        ///    NestedStructProperty = new StructForTest1()
        ///    {
        ///        myIntvalue = 8,
        ///        myStringValue = &quot;Hey&quot;
        ///    }
        ///};
        ///
        ///// Do not compile 
        ///classStructContainer.NestedStructProperty.myIntvalue = 9;
        ///
        ///return $&quot;Result {classStructContainer.NestedStructProperty.myStringValue} {classStructContainer.NestedStructProperty.myIntvalue}&quot;;
        /// 的當地語系化字串。
        /// </summary>
        public static string Script0058 {
            get {
                return ResourceManager.GetString("Script0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0059 */
        ///otherStruct = new StructForTest4();
        ///
        ///otherStruct.AnOtherIntValue = 5;
        ///otherStruct.NestedStruct = new StructForTest3()
        ///{
        ///    MyIntvalue = 8,
        ///    MyStringValue = &quot;Hey&quot;
        ///};
        ///
        ///// Do not compile 
        ///otherStruct.NestedStruct.MyIntvalue = 9;
        ///
        ///return $&quot;Result {otherStruct.NestedStruct.MyStringValue} {otherStruct.NestedStruct.MyIntvalue}, {otherStruct.AnOtherIntValue}&quot;; 的當地語系化字串。
        /// </summary>
        public static string Script0059 {
            get {
                return ResourceManager.GetString("Script0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0060 */
        ///var x = 4;
        ///var textVar = &quot;A text for {0} test&quot;;
        ///
        ///return string.Format(textVar, x); 的當地語系化字串。
        /// </summary>
        public static string Script0060 {
            get {
                return ResourceManager.GetString("Script0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0061 */
        ///var x = new List&lt;int&gt; {1,2,3,4};
        ///x.Json 的當地語系化字串。
        /// </summary>
        public static string Script0061 {
            get {
                return ResourceManager.GetString("Script0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0062 */
        ///var x = new List&lt;int&gt; {1,2,3,4} 的當地語系化字串。
        /// </summary>
        public static string Script0062 {
            get {
                return ResourceManager.GetString("Script0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0063 */
        ///int x = 3;
        ///
        ///return x + 2; 的當地語系化字串。
        /// </summary>
        public static string Script0063 {
            get {
                return ResourceManager.GetString("Script0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0064 */
        ///float x = 3.5f;
        ///
        ///return x + 2; 的當地語系化字串。
        /// </summary>
        public static string Script0064 {
            get {
                return ResourceManager.GetString("Script0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0065 */
        ///dynamic x = 6;
        ///
        ///return x + 2; 的當地語系化字串。
        /// </summary>
        public static string Script0065 {
            get {
                return ResourceManager.GetString("Script0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0066 */
        ///string test = &quot;&quot;;
        ///
        ///for(int x = 0; x &lt; 5; x++)
        ///{
        ///	test += x.ToString() + &quot;,&quot;;
        ///}
        ///
        ///return test; 的當地語系化字串。
        /// </summary>
        public static string Script0066 {
            get {
                return ResourceManager.GetString("Script0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0067 */
        ///List&lt;int&gt; myList = new List&lt;int&gt;{1, 2, 3, 4};
        ///
        ///myList.Json; 的當地語系化字串。
        /// </summary>
        public static string Script0067 {
            get {
                return ResourceManager.GetString("Script0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0068 */
        ///List&lt;int&gt; myList = new List&lt;int&gt;{1, 2, 3, 4};
        ///
        ///int a = 0;
        ///
        ///myList.ForEach(v =&gt; a += v);
        ///
        ///return a; 的當地語系化字串。
        /// </summary>
        public static string Script0068 {
            get {
                return ResourceManager.GetString("Script0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0069 */
        ///List&lt;int&gt; myList = new List&lt;int&gt;{1, 2, 3, 4};
        ///
        ///string text = &quot;&quot;;
        ///
        ///myList.ForEach(v =&gt;
        ///{
        ///	text += v.ToString() + &quot;;&quot;;
        ///});
        ///
        ///return text; 的當地語系化字串。
        /// </summary>
        public static string Script0069 {
            get {
                return ResourceManager.GetString("Script0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0070 */
        ///var e = new Exception(&quot;Must not be thrown&quot;);
        ///
        ///return 1+2; 的當地語系化字串。
        /// </summary>
        public static string Script0070 {
            get {
                return ResourceManager.GetString("Script0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0071 */
        ///var myVar = null;
        ///
        ///myVar ??= &quot;First Null-coalescing assignation&quot;;
        ///myVar ??= &quot;Second Null-coalescing assignation&quot;;
        ///
        ///return myVar; 的當地語系化字串。
        /// </summary>
        public static string Script0071 {
            get {
                return ResourceManager.GetString("Script0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0072 */
        ///var newList = new(List&lt;string&gt;);
        ///
        ///newList.Add(&quot;hello&quot;);
        ///
        ///return newList[0]; 的當地語系化字串。
        /// </summary>
        public static string Script0072 {
            get {
                return ResourceManager.GetString("Script0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0073 */
        ///var newList = new List&lt;string&gt;();
        ///
        ///newList.Add(&quot;hello&quot;);
        ///
        ///return newList[0]; 的當地語系化字串。
        /// </summary>
        public static string Script0073 {
            get {
                return ResourceManager.GetString("Script0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0073 */
        ///var newWord = &quot;hello&quot;;
        ///
        ///return newWord; 的當地語系化字串。
        /// </summary>
        public static string Script0074 {
            get {
                return ResourceManager.GetString("Script0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0100 */
        ///var dictionary = new Dictionary&lt;string, object&gt;();
        ///dictionary.Add(&quot;x&quot;, 5);
        ///object number = null;
        ///if (dictionary.TryGetValue(&quot;x&quot;, out number))
        ///	return number;
        ///return 0; 的當地語系化字串。
        /// </summary>
        public static string Script0100 {
            get {
                return ResourceManager.GetString("Script0100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /* Script0101 */
        ///var dictionary = new Dictionary&lt;string, object&gt;();
        ///dictionary.Add(&quot;x&quot;, 5);
        ///object number = 10;
        ///if (dictionary.TryGetValue(&quot;x&quot;, out number))
        ///	return number;
        ///return 0; 的當地語系化字串。
        /// </summary>
        public static string Script0101 {
            get {
                return ResourceManager.GetString("Script0101", resourceCulture);
            }
        }
    }
}
